### ISSUE TITLE
Jest crashes with "illegal hardware instruction"

### ISSUE THREAD

**Issue by HermanBilous** [Codex-/swc-plugin-import-meta-env#33]
I'm using this plugin with jest and when I run tests via `jest` I receive an error: `zsh: illegal hardware instruction  jest`. I created a repository that reproduces this issue for me: https://github.com/HermanBilous/test-swc-jest

My system info is:
```
Software:
    System Software Overview:
      System Version: macOS 13.6 (22G120)
      Kernel Version: Darwin 22.6.0
Hardware:
    Hardware Overview:
      Processor Name: Quad-Core Intel Core i7
      Processor Speed: 2,3 GHz
```

Node version is 20.11.0

Note: downgrading to 0.3.0 fixes the issue

**Comment by Codex-** [comment]
Strange, I'll take a look, thanks for the repro
